"""Adding invite links

Revision ID: 2c0bc673ab55
Revises: ccd69623c86a
Create Date: 2022-07-08 18:38:04.520732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0bc673ab55'
down_revision = 'ccd69623c86a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipal', sa.Column('invite_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipal', 'invite_link')
    # ### end Alembic commands ###
