"""Update profiles

Revision ID: 36a3ad8033bb
Revises: 3be1477e3cf0
Create Date: 2022-07-14 22:23:55.189595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36a3ad8033bb'
down_revision = '3be1477e3cf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_activity_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('eco_activity_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['eco_activity_id'], ['eco_activity.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eco_activity_profile_eco_activity_id'), 'eco_activity_profile', ['eco_activity_id'], unique=False)
    op.create_index(op.f('ix_eco_activity_profile_id'), 'eco_activity_profile', ['id'], unique=False)
    op.create_index(op.f('ix_eco_activity_profile_profile_id'), 'eco_activity_profile', ['profile_id'], unique=False)
    op.add_column('profile', sa.Column('municipal_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_profile_municipal_id'), 'profile', ['municipal_id'], unique=False)
    op.create_foreign_key(None, 'profile', 'municipal', ['municipal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_index(op.f('ix_profile_municipal_id'), table_name='profile')
    op.drop_column('profile', 'municipal_id')
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_tasksetmeta_pkey'),
    sa.UniqueConstraint('taskset_id', name='celery_tasksetmeta_taskset_id_key')
    )
    op.drop_index(op.f('ix_eco_activity_profile_profile_id'), table_name='eco_activity_profile')
    op.drop_index(op.f('ix_eco_activity_profile_id'), table_name='eco_activity_profile')
    op.drop_index(op.f('ix_eco_activity_profile_eco_activity_id'), table_name='eco_activity_profile')
    op.drop_table('eco_activity_profile')
    # ### end Alembic commands ###
