"""Adding volunteer type

Revision ID: 3be1477e3cf0
Revises: 8d8acbdc52a5
Create Date: 2022-07-12 16:21:11.005832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be1477e3cf0'
down_revision = '8d8acbdc52a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_type_id'), 'volunteer_type', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_type_name'), 'volunteer_type', ['name'], unique=False)
    op.create_table('volunteer_type_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('volunteer_type_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['volunteer_type_id'], ['volunteer_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_type_event_event_id'), 'volunteer_type_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_volunteer_type_event_id'), 'volunteer_type_event', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_type_event_volunteer_type_id'), 'volunteer_type_event', ['volunteer_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_type_event_volunteer_type_id'), table_name='volunteer_type_event')
    op.drop_index(op.f('ix_volunteer_type_event_id'), table_name='volunteer_type_event')
    op.drop_index(op.f('ix_volunteer_type_event_event_id'), table_name='volunteer_type_event')
    op.drop_table('volunteer_type_event')
    op.drop_index(op.f('ix_volunteer_type_name'), table_name='volunteer_type')
    op.drop_index(op.f('ix_volunteer_type_id'), table_name='volunteer_type')
    op.drop_table('volunteer_type')
    # ### end Alembic commands ###
