"""Update profiles

Revision ID: 596e89d532ed
Revises: 36a3ad8033bb
Create Date: 2022-07-15 08:03:41.832778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596e89d532ed'
down_revision = '36a3ad8033bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_type_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('volunteer_type_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['volunteer_type_id'], ['volunteer_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_type_profile_id'), 'volunteer_type_profile', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_type_profile_profile_id'), 'volunteer_type_profile', ['profile_id'], unique=False)
    op.create_index(op.f('ix_volunteer_type_profile_volunteer_type_id'), 'volunteer_type_profile', ['volunteer_type_id'], unique=False)
    op.add_column('profile', sa.Column('is_event_organizer', sa.Boolean(), nullable=True))
    op.add_column('profile', sa.Column('name', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_profile_is_event_organizer'), 'profile', ['is_event_organizer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_is_event_organizer'), table_name='profile')
    op.drop_column('profile', 'age')
    op.drop_column('profile', 'name')
    op.drop_column('profile', 'is_event_organizer')
    op.drop_index(op.f('ix_volunteer_type_profile_volunteer_type_id'), table_name='volunteer_type_profile')
    op.drop_index(op.f('ix_volunteer_type_profile_profile_id'), table_name='volunteer_type_profile')
    op.drop_index(op.f('ix_volunteer_type_profile_id'), table_name='volunteer_type_profile')
    op.drop_table('volunteer_type_profile')
    # ### end Alembic commands ###
