"""update

Revision ID: 8d8acbdc52a5
Revises: 2c0bc673ab55
Create Date: 2022-07-12 14:29:30.395300

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
from database import EventType

revision = '8d8acbdc52a5'
down_revision = '2c0bc673ab55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(choices=EventType), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=False)
    op.create_index(op.f('ix_event_organization_id'), 'event', ['organization_id'], unique=False)
    op.create_index(op.f('ix_event_type'), 'event', ['type'], unique=False)
    op.create_table('district_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_event_district_id'), 'district_event', ['district_id'], unique=False)
    op.create_index(op.f('ix_district_event_event_id'), 'district_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_district_event_id'), 'district_event', ['id'], unique=False)
    op.create_table('eco_activity_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eco_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['eco_activity_id'], ['eco_activity.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eco_activity_event_eco_activity_id'), 'eco_activity_event', ['eco_activity_id'], unique=False)
    op.create_index(op.f('ix_eco_activity_event_event_id'), 'eco_activity_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_eco_activity_event_id'), 'eco_activity_event', ['id'], unique=False)
    op.create_table('mailing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('start_execute_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_execute_datetime', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_end_execute_datetime'), 'mailing', ['end_execute_datetime'], unique=False)
    op.create_index(op.f('ix_mailing_event_id'), 'mailing', ['event_id'], unique=False)
    op.create_index(op.f('ix_mailing_id'), 'mailing', ['id'], unique=False)
    op.create_index(op.f('ix_mailing_is_executed'), 'mailing', ['is_executed'], unique=False)
    op.create_index(op.f('ix_mailing_start_execute_datetime'), 'mailing', ['start_execute_datetime'], unique=False)
    op.create_table('municipal_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('municipal_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['municipal_id'], ['municipal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipal_event_event_id'), 'municipal_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_municipal_event_id'), 'municipal_event', ['id'], unique=False)
    op.create_index(op.f('ix_municipal_event_municipal_id'), 'municipal_event', ['municipal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipal_event_municipal_id'), table_name='municipal_event')
    op.drop_index(op.f('ix_municipal_event_id'), table_name='municipal_event')
    op.drop_index(op.f('ix_municipal_event_event_id'), table_name='municipal_event')
    op.drop_table('municipal_event')
    op.drop_index(op.f('ix_mailing_start_execute_datetime'), table_name='mailing')
    op.drop_index(op.f('ix_mailing_is_executed'), table_name='mailing')
    op.drop_index(op.f('ix_mailing_id'), table_name='mailing')
    op.drop_index(op.f('ix_mailing_event_id'), table_name='mailing')
    op.drop_index(op.f('ix_mailing_end_execute_datetime'), table_name='mailing')
    op.drop_table('mailing')
    op.drop_index(op.f('ix_eco_activity_event_id'), table_name='eco_activity_event')
    op.drop_index(op.f('ix_eco_activity_event_event_id'), table_name='eco_activity_event')
    op.drop_index(op.f('ix_eco_activity_event_eco_activity_id'), table_name='eco_activity_event')
    op.drop_table('eco_activity_event')
    op.drop_index(op.f('ix_district_event_id'), table_name='district_event')
    op.drop_index(op.f('ix_district_event_event_id'), table_name='district_event')
    op.drop_index(op.f('ix_district_event_district_id'), table_name='district_event')
    op.drop_table('district_event')
    op.drop_index(op.f('ix_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_organization_id'), table_name='event')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
