version: '3.9'
services:
  database:
    image: postgres:13.4-buster
    restart: on-failure
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/backups:/backups
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}

  redis:
    image: redis
    restart: always
    command: "redis-server --requirepass ${REDIS_PASSWORD:-password}"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  bot:
    image: bot
    depends_on:
      - database
      - redis
      - worker
    command: python3 cli.py
    restart: on-failure
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMINS: ${ADMINS}

  worker:
    image: bot
    depends_on:
      - database
      - redis
    command: celery -A workers.celery worker -l INFO
    restart: on-failure
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMINS: ${ADMINS}

  admin:
    build:
      context: .
      dockerfile: ./docker/admin/Dockerfile
    depends_on:
      - database
    restart: on-failure
    command: gunicorn -c gunicorn_conf.py wsgi:app
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMINS: ${ADMINS}

  nginx:
    build: ./docker/nginx
    ports:
      - "1337:80"
    depends_on:
      - admin

volumes:
  redis_data:
    driver: local